master_node:
   hosts:
     master:
       ansible_ssh_host: 192.168.2.10
       ansible_user: vagrant
       ansible_password: vagrant
       ansible_ssh_extra_args: '-o IdentityFile=~/.vagrant.d/insecure_private_key'
       hostname: master
